# Generated by Django 3.2.3 on 2021-05-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prefer_movies',
        ),
    ]
