# Generated by Django 3.2.3 on 2021-05-22 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(blank=True)),
                ('video', models.BooleanField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=100)),
                ('backdrop_path', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('original_language', models.CharField(blank=True, max_length=50)),
                ('release_date', models.DateField(blank=True)),
                ('popularity', models.FloatField(blank=True)),
                ('vote_average', models.FloatField(blank=True)),
                ('vote_count', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='prefer_users',
            field=models.ManyToManyField(related_name='prefer_movies', through='movies.Prefer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('movies', models.ManyToManyField(related_name='genres', to='movies.Movie')),
            ],
        ),
    ]
